# https://starship.rs/config

# https://starship.rs/config/#shell
[shell]
disabled = false

# https://starship.rs/config/#shlvl
[shlvl]
disabled = false
threshold = 3

# https://starship.rs/config/#battery-display
[[battery.display]]
threshold = 80
style = "yellow"

# https://starship.rs/config/#git-branch
[git_branch]
symbol = "ğŸŒ± "

# https://starship.rs/config/#git-status
[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨${count}"
behind = "ğŸ¢${count}"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\(${count}\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

# https://starship.rs/config/#kubernetes
[kubernetes]
symbol = "â›´  "
style = "dimmed green"
disabled = false

# https://starship.rs/config/#terraform
[terraform]

# https://starship.rs/config/#nix-shell
[nix_shell]

# https://starship.rs/config/#aws
[aws]
symbol = 'ğŸ…° '
