# https://starship.rs/config

[shlvl]
disabled = false
threshold = 3

[[battery.display]]
threshold = 80
style = "yellow"

[git_branch]
symbol = "ğŸŒ± "

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨${count}"
behind = "ğŸ¢${count}"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\(${count}\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[kubernetes]
symbol = "â›´  "
style = "dimmed green"
disabled = false

[terraform]

[nix_shell]

[aws]
symbol = 'ğŸ…° '
